max-expression-operators = 4
max-if-operators = 0
max-control-flow-depth = 3
max-function-lines = 20
min-case-chain-length = 3
min-object-lookup-chain-length = 3
min-dirname-match-depth = 3
ignore = ["LEG025", "LEG035", "LEG039"]
comment-matchers = []
